package zjs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import zjs.entity.AccBusinessadmissibility;
import zjs.entity.AccBusinessadmissibilityExample;
@Repository
public interface AccBusinessadmissibilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_businessadmissibility
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int countByExample(AccBusinessadmissibilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_businessadmissibility
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByExample(AccBusinessadmissibilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_businessadmissibility
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_businessadmissibility
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insert(AccBusinessadmissibility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_businessadmissibility
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insertSelective(AccBusinessadmissibility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_businessadmissibility
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    List<AccBusinessadmissibility> selectByExample(AccBusinessadmissibilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_businessadmissibility
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    AccBusinessadmissibility selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_businessadmissibility
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") AccBusinessadmissibility record, @Param("example") AccBusinessadmissibilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_businessadmissibility
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExample(@Param("record") AccBusinessadmissibility record, @Param("example") AccBusinessadmissibilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_businessadmissibility
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKeySelective(AccBusinessadmissibility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_businessadmissibility
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKey(AccBusinessadmissibility record);
}