package zjs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import zjs.entity.BasArea;
import zjs.entity.BasAreaExample;
@Repository
public interface BasAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_area
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int countByExample(BasAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_area
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByExample(BasAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_area
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_area
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insert(BasArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_area
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insertSelective(BasArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_area
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    List<BasArea> selectByExample(BasAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_area
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    BasArea selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_area
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") BasArea record, @Param("example") BasAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_area
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExample(@Param("record") BasArea record, @Param("example") BasAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_area
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKeySelective(BasArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_area
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKey(BasArea record);
}