package zjs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import zjs.entity.BasBasicarchives;
import zjs.entity.BasBasicarchivesExample;
@Repository
public interface BasBasicarchivesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_basicarchives
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int countByExample(BasBasicarchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_basicarchives
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByExample(BasBasicarchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_basicarchives
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_basicarchives
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insert(BasBasicarchives record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_basicarchives
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insertSelective(BasBasicarchives record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_basicarchives
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    List<BasBasicarchives> selectByExample(BasBasicarchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_basicarchives
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    BasBasicarchives selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_basicarchives
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") BasBasicarchives record, @Param("example") BasBasicarchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_basicarchives
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExample(@Param("record") BasBasicarchives record, @Param("example") BasBasicarchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_basicarchives
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKeySelective(BasBasicarchives record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_basicarchives
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKey(BasBasicarchives record);
}