package zjs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import zjs.entity.DisPropagandatask;
import zjs.entity.DisPropagandataskExample;
@Repository
public interface DisPropagandataskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_propagandatask
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int countByExample(DisPropagandataskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_propagandatask
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByExample(DisPropagandataskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_propagandatask
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_propagandatask
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insert(DisPropagandatask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_propagandatask
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insertSelective(DisPropagandatask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_propagandatask
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    List<DisPropagandatask> selectByExample(DisPropagandataskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_propagandatask
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    DisPropagandatask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_propagandatask
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") DisPropagandatask record, @Param("example") DisPropagandataskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_propagandatask
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExample(@Param("record") DisPropagandatask record, @Param("example") DisPropagandataskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_propagandatask
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKeySelective(DisPropagandatask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_propagandatask
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKey(DisPropagandatask record);
}