package zjs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import zjs.entity.LogLogisticsdetails;
import zjs.entity.LogLogisticsdetailsExample;
@Repository
public interface LogLogisticsdetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logisticsdetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int countByExample(LogLogisticsdetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logisticsdetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByExample(LogLogisticsdetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logisticsdetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logisticsdetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insert(LogLogisticsdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logisticsdetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insertSelective(LogLogisticsdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logisticsdetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    List<LogLogisticsdetails> selectByExample(LogLogisticsdetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logisticsdetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    LogLogisticsdetails selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logisticsdetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") LogLogisticsdetails record, @Param("example") LogLogisticsdetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logisticsdetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExample(@Param("record") LogLogisticsdetails record, @Param("example") LogLogisticsdetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logisticsdetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKeySelective(LogLogisticsdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logisticsdetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKey(LogLogisticsdetails record);
}