package zjs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import zjs.entity.LogLogisticstransfer;
import zjs.entity.LogLogisticstransferExample;
@Repository
public interface LogLogisticstransferMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logisticstransfer
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int countByExample(LogLogisticstransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logisticstransfer
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByExample(LogLogisticstransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logisticstransfer
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logisticstransfer
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insert(LogLogisticstransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logisticstransfer
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insertSelective(LogLogisticstransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logisticstransfer
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    List<LogLogisticstransfer> selectByExample(LogLogisticstransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logisticstransfer
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    LogLogisticstransfer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logisticstransfer
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") LogLogisticstransfer record, @Param("example") LogLogisticstransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logisticstransfer
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExample(@Param("record") LogLogisticstransfer record, @Param("example") LogLogisticstransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logisticstransfer
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKeySelective(LogLogisticstransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logisticstransfer
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKey(LogLogisticstransfer record);
}