package zjs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import zjs.entity.PacStockitem;
import zjs.entity.PacStockitemExample;
import zjs.entity.PacStockitemKey;
@Repository
public interface PacStockitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pac_stockitem
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int countByExample(PacStockitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pac_stockitem
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByExample(PacStockitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pac_stockitem
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByPrimaryKey(PacStockitemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pac_stockitem
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insert(PacStockitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pac_stockitem
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insertSelective(PacStockitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pac_stockitem
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    List<PacStockitem> selectByExample(PacStockitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pac_stockitem
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    PacStockitem selectByPrimaryKey(PacStockitemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pac_stockitem
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") PacStockitem record, @Param("example") PacStockitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pac_stockitem
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExample(@Param("record") PacStockitem record, @Param("example") PacStockitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pac_stockitem
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKeySelective(PacStockitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pac_stockitem
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKey(PacStockitem record);
}