package zjs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import zjs.entity.PacStock;
import zjs.entity.PacStockExample;
@Repository
public interface PacStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pac_stock
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int countByExample(PacStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pac_stock
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByExample(PacStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pac_stock
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insert(PacStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pac_stock
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insertSelective(PacStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pac_stock
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    List<PacStock> selectByExample(PacStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pac_stock
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") PacStock record, @Param("example") PacStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pac_stock
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExample(@Param("record") PacStock record, @Param("example") PacStockExample example);
}