package zjs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import zjs.entity.SorCheckbounddetails;
import zjs.entity.SorCheckbounddetailsExample;
@Repository
public interface SorCheckbounddetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_checkbounddetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int countByExample(SorCheckbounddetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_checkbounddetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByExample(SorCheckbounddetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_checkbounddetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_checkbounddetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insert(SorCheckbounddetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_checkbounddetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insertSelective(SorCheckbounddetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_checkbounddetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    List<SorCheckbounddetails> selectByExample(SorCheckbounddetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_checkbounddetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    SorCheckbounddetails selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_checkbounddetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") SorCheckbounddetails record, @Param("example") SorCheckbounddetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_checkbounddetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExample(@Param("record") SorCheckbounddetails record, @Param("example") SorCheckbounddetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_checkbounddetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKeySelective(SorCheckbounddetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_checkbounddetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKey(SorCheckbounddetails record);
}