package zjs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import zjs.entity.SorPackagedetails;
import zjs.entity.SorPackagedetailsExample;
@Repository
public interface SorPackagedetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_packagedetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int countByExample(SorPackagedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_packagedetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByExample(SorPackagedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_packagedetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_packagedetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insert(SorPackagedetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_packagedetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insertSelective(SorPackagedetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_packagedetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    List<SorPackagedetails> selectByExample(SorPackagedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_packagedetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    SorPackagedetails selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_packagedetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") SorPackagedetails record, @Param("example") SorPackagedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_packagedetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExample(@Param("record") SorPackagedetails record, @Param("example") SorPackagedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_packagedetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKeySelective(SorPackagedetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_packagedetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKey(SorPackagedetails record);
}