package zjs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import zjs.entity.BasAssociatedaddress;
import zjs.entity.BasAssociatedaddressExample;
@Repository
public interface BasAssociatedaddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_associatedaddress
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int countByExample(BasAssociatedaddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_associatedaddress
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByExample(BasAssociatedaddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_associatedaddress
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_associatedaddress
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insert(BasAssociatedaddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_associatedaddress
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insertSelective(BasAssociatedaddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_associatedaddress
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    List<BasAssociatedaddress> selectByExample(BasAssociatedaddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_associatedaddress
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    BasAssociatedaddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_associatedaddress
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") BasAssociatedaddress record, @Param("example") BasAssociatedaddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_associatedaddress
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExample(@Param("record") BasAssociatedaddress record, @Param("example") BasAssociatedaddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_associatedaddress
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKeySelective(BasAssociatedaddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_associatedaddress
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKey(BasAssociatedaddress record);
}