package zjs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import zjs.entity.BasBasicarchivesentry;
import zjs.entity.BasBasicarchivesentryExample;
@Repository
public interface BasBasicarchivesentryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_basicarchivesentry
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int countByExample(BasBasicarchivesentryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_basicarchivesentry
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByExample(BasBasicarchivesentryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_basicarchivesentry
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_basicarchivesentry
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insert(BasBasicarchivesentry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_basicarchivesentry
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insertSelective(BasBasicarchivesentry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_basicarchivesentry
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    List<BasBasicarchivesentry> selectByExample(BasBasicarchivesentryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_basicarchivesentry
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    BasBasicarchivesentry selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_basicarchivesentry
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") BasBasicarchivesentry record, @Param("example") BasBasicarchivesentryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_basicarchivesentry
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExample(@Param("record") BasBasicarchivesentry record, @Param("example") BasBasicarchivesentryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_basicarchivesentry
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKeySelective(BasBasicarchivesentry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_basicarchivesentry
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKey(BasBasicarchivesentry record);
}