package zjs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import zjs.entity.BasDeliverystandard;
import zjs.entity.BasDeliverystandardExample;
@Repository
public interface BasDeliverystandardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_deliverystandard
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int countByExample(BasDeliverystandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_deliverystandard
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByExample(BasDeliverystandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_deliverystandard
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_deliverystandard
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insert(BasDeliverystandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_deliverystandard
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insertSelective(BasDeliverystandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_deliverystandard
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    List<BasDeliverystandard> selectByExample(BasDeliverystandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_deliverystandard
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    BasDeliverystandard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_deliverystandard
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") BasDeliverystandard record, @Param("example") BasDeliverystandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_deliverystandard
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExample(@Param("record") BasDeliverystandard record, @Param("example") BasDeliverystandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_deliverystandard
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKeySelective(BasDeliverystandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_deliverystandard
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKey(BasDeliverystandard record);
}