package zjs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import zjs.entity.BiglogLogisticscontroltable;
import zjs.entity.BiglogLogisticscontroltableExample;
@Repository
public interface BiglogLogisticscontroltableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biglog_logisticscontroltable
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int countByExample(BiglogLogisticscontroltableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biglog_logisticscontroltable
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByExample(BiglogLogisticscontroltableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biglog_logisticscontroltable
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biglog_logisticscontroltable
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insert(BiglogLogisticscontroltable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biglog_logisticscontroltable
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insertSelective(BiglogLogisticscontroltable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biglog_logisticscontroltable
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    List<BiglogLogisticscontroltable> selectByExample(BiglogLogisticscontroltableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biglog_logisticscontroltable
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    BiglogLogisticscontroltable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biglog_logisticscontroltable
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") BiglogLogisticscontroltable record, @Param("example") BiglogLogisticscontroltableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biglog_logisticscontroltable
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExample(@Param("record") BiglogLogisticscontroltable record, @Param("example") BiglogLogisticscontroltableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biglog_logisticscontroltable
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKeySelective(BiglogLogisticscontroltable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biglog_logisticscontroltable
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKey(BiglogLogisticscontroltable record);
}