package zjs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import zjs.entity.DisDispatchhistory;
import zjs.entity.DisDispatchhistoryExample;
@Repository
public interface DisDispatchhistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_dispatchhistory
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int countByExample(DisDispatchhistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_dispatchhistory
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByExample(DisDispatchhistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_dispatchhistory
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_dispatchhistory
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insert(DisDispatchhistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_dispatchhistory
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insertSelective(DisDispatchhistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_dispatchhistory
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    List<DisDispatchhistory> selectByExample(DisDispatchhistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_dispatchhistory
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    DisDispatchhistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_dispatchhistory
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") DisDispatchhistory record, @Param("example") DisDispatchhistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_dispatchhistory
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExample(@Param("record") DisDispatchhistory record, @Param("example") DisDispatchhistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_dispatchhistory
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKeySelective(DisDispatchhistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_dispatchhistory
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKey(DisDispatchhistory record);
}