package zjs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import zjs.entity.LogLogistics;
import zjs.entity.LogLogisticsExample;
@Repository
public interface LogLogisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logistics
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int countByExample(LogLogisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logistics
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByExample(LogLogisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logistics
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logistics
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insert(LogLogistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logistics
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insertSelective(LogLogistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logistics
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    List<LogLogistics> selectByExample(LogLogisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logistics
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    LogLogistics selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logistics
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") LogLogistics record, @Param("example") LogLogisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logistics
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExample(@Param("record") LogLogistics record, @Param("example") LogLogisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logistics
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKeySelective(LogLogistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_logistics
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKey(LogLogistics record);
}