package zjs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import zjs.entity.SorOutbounddetails;
import zjs.entity.SorOutbounddetailsExample;
@Repository
public interface SorOutbounddetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_outbounddetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int countByExample(SorOutbounddetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_outbounddetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByExample(SorOutbounddetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_outbounddetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_outbounddetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insert(SorOutbounddetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_outbounddetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insertSelective(SorOutbounddetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_outbounddetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    List<SorOutbounddetails> selectByExample(SorOutbounddetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_outbounddetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    SorOutbounddetails selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_outbounddetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") SorOutbounddetails record, @Param("example") SorOutbounddetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_outbounddetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExample(@Param("record") SorOutbounddetails record, @Param("example") SorOutbounddetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_outbounddetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKeySelective(SorOutbounddetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_outbounddetails
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKey(SorOutbounddetails record);
}