package zjs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import zjs.entity.SorPackage;
import zjs.entity.SorPackageExample;
@Repository
public interface SorPackageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_package
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int countByExample(SorPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_package
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByExample(SorPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_package
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_package
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insert(SorPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_package
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int insertSelective(SorPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_package
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    List<SorPackage> selectByExample(SorPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_package
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    SorPackage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_package
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") SorPackage record, @Param("example") SorPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_package
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByExample(@Param("record") SorPackage record, @Param("example") SorPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_package
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKeySelective(SorPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sor_package
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    int updateByPrimaryKey(SorPackage record);
}