package zjs.entity;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;
@Data
public class BasDeliverystandard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_deliverystandard.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_deliverystandard.Name
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_deliverystandard.MinWeight
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private BigDecimal minweight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_deliverystandard.MaxWeight
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private BigDecimal maxweight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_deliverystandard.OperatorID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer operatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_deliverystandard.OperationUnitID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer operationunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_deliverystandard.OperationTime
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Date operationtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_deliverystandard.ID
     *
     * @return the value of bas_deliverystandard.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_deliverystandard.ID
     *
     * @param id the value for bas_deliverystandard.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_deliverystandard.Name
     *
     * @return the value of bas_deliverystandard.Name
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_deliverystandard.Name
     *
     * @param name the value for bas_deliverystandard.Name
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_deliverystandard.MinWeight
     *
     * @return the value of bas_deliverystandard.MinWeight
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public BigDecimal getMinweight() {
        return minweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_deliverystandard.MinWeight
     *
     * @param minweight the value for bas_deliverystandard.MinWeight
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setMinweight(BigDecimal minweight) {
        this.minweight = minweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_deliverystandard.MaxWeight
     *
     * @return the value of bas_deliverystandard.MaxWeight
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public BigDecimal getMaxweight() {
        return maxweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_deliverystandard.MaxWeight
     *
     * @param maxweight the value for bas_deliverystandard.MaxWeight
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setMaxweight(BigDecimal maxweight) {
        this.maxweight = maxweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_deliverystandard.OperatorID
     *
     * @return the value of bas_deliverystandard.OperatorID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_deliverystandard.OperatorID
     *
     * @param operatorid the value for bas_deliverystandard.OperatorID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setOperatorid(Integer operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_deliverystandard.OperationUnitID
     *
     * @return the value of bas_deliverystandard.OperationUnitID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getOperationunitid() {
        return operationunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_deliverystandard.OperationUnitID
     *
     * @param operationunitid the value for bas_deliverystandard.OperationUnitID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setOperationunitid(Integer operationunitid) {
        this.operationunitid = operationunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_deliverystandard.OperationTime
     *
     * @return the value of bas_deliverystandard.OperationTime
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Date getOperationtime() {
        return operationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_deliverystandard.OperationTime
     *
     * @param operationtime the value for bas_deliverystandard.OperationTime
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setOperationtime(Date operationtime) {
        this.operationtime = operationtime;
    }
}