package zjs.entity;

import lombok.Data;

@Data
public class PacStockitem extends PacStockitemKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pac_stockitem.GoodsName
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String goodsname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pac_stockitem.StorageNum
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer storagenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pac_stockitem.PlannedPrice
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Float plannedprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pac_stockitem.Specifications
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String specifications;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pac_stockitem.type
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Boolean type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pac_stockitem.Status
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pac_stockitem.GoodsName
     *
     * @return the value of pac_stockitem.GoodsName
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pac_stockitem.GoodsName
     *
     * @param goodsname the value for pac_stockitem.GoodsName
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname == null ? null : goodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pac_stockitem.StorageNum
     *
     * @return the value of pac_stockitem.StorageNum
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getStoragenum() {
        return storagenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pac_stockitem.StorageNum
     *
     * @param storagenum the value for pac_stockitem.StorageNum
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setStoragenum(Integer storagenum) {
        this.storagenum = storagenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pac_stockitem.PlannedPrice
     *
     * @return the value of pac_stockitem.PlannedPrice
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Float getPlannedprice() {
        return plannedprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pac_stockitem.PlannedPrice
     *
     * @param plannedprice the value for pac_stockitem.PlannedPrice
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setPlannedprice(Float plannedprice) {
        this.plannedprice = plannedprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pac_stockitem.Specifications
     *
     * @return the value of pac_stockitem.Specifications
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getSpecifications() {
        return specifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pac_stockitem.Specifications
     *
     * @param specifications the value for pac_stockitem.Specifications
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setSpecifications(String specifications) {
        this.specifications = specifications == null ? null : specifications.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pac_stockitem.type
     *
     * @return the value of pac_stockitem.type
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Boolean getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pac_stockitem.type
     *
     * @param type the value for pac_stockitem.type
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setType(Boolean type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pac_stockitem.Status
     *
     * @return the value of pac_stockitem.Status
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pac_stockitem.Status
     *
     * @param status the value for pac_stockitem.Status
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}