package zjs.entity;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;
@Data
public class SorCheckbounddetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sor_checkbounddetails.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sor_checkbounddetails.PackageID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String packageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sor_checkbounddetails.CargoCount
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer cargocount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sor_checkbounddetails.Weight
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private BigDecimal weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sor_checkbounddetails.Volume
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private BigDecimal volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sor_checkbounddetails.CargoType
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Boolean cargotype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sor_checkbounddetails.Direction
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String direction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sor_checkbounddetails.StoragePerson
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer storageperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sor_checkbounddetails.StorageDate
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Date storagedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sor_checkbounddetails.ID
     *
     * @return the value of sor_checkbounddetails.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sor_checkbounddetails.ID
     *
     * @param id the value for sor_checkbounddetails.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sor_checkbounddetails.PackageID
     *
     * @return the value of sor_checkbounddetails.PackageID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getPackageid() {
        return packageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sor_checkbounddetails.PackageID
     *
     * @param packageid the value for sor_checkbounddetails.PackageID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setPackageid(String packageid) {
        this.packageid = packageid == null ? null : packageid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sor_checkbounddetails.CargoCount
     *
     * @return the value of sor_checkbounddetails.CargoCount
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getCargocount() {
        return cargocount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sor_checkbounddetails.CargoCount
     *
     * @param cargocount the value for sor_checkbounddetails.CargoCount
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setCargocount(Integer cargocount) {
        this.cargocount = cargocount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sor_checkbounddetails.Weight
     *
     * @return the value of sor_checkbounddetails.Weight
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sor_checkbounddetails.Weight
     *
     * @param weight the value for sor_checkbounddetails.Weight
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sor_checkbounddetails.Volume
     *
     * @return the value of sor_checkbounddetails.Volume
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public BigDecimal getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sor_checkbounddetails.Volume
     *
     * @param volume the value for sor_checkbounddetails.Volume
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setVolume(BigDecimal volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sor_checkbounddetails.CargoType
     *
     * @return the value of sor_checkbounddetails.CargoType
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Boolean getCargotype() {
        return cargotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sor_checkbounddetails.CargoType
     *
     * @param cargotype the value for sor_checkbounddetails.CargoType
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setCargotype(Boolean cargotype) {
        this.cargotype = cargotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sor_checkbounddetails.Direction
     *
     * @return the value of sor_checkbounddetails.Direction
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sor_checkbounddetails.Direction
     *
     * @param direction the value for sor_checkbounddetails.Direction
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setDirection(String direction) {
        this.direction = direction == null ? null : direction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sor_checkbounddetails.StoragePerson
     *
     * @return the value of sor_checkbounddetails.StoragePerson
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getStorageperson() {
        return storageperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sor_checkbounddetails.StoragePerson
     *
     * @param storageperson the value for sor_checkbounddetails.StoragePerson
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setStorageperson(Integer storageperson) {
        this.storageperson = storageperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sor_checkbounddetails.StorageDate
     *
     * @return the value of sor_checkbounddetails.StorageDate
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Date getStoragedate() {
        return storagedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sor_checkbounddetails.StorageDate
     *
     * @param storagedate the value for sor_checkbounddetails.StorageDate
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setStoragedate(Date storagedate) {
        this.storagedate = storagedate;
    }
}