package zjs.entity;

import lombok.Data;

import java.util.Date;
@Data
public class AccWorkorder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_workorder.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_workorder.BusinessNoticeNo
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String businessnoticeno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_workorder.JobNo
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String jobno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_workorder.JobType
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Boolean jobtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_workorder.PickupStatus
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Boolean pickupstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_workorder.ShortMessageInt
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer shortmessageint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_workorder.WorkGenerationTime
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Date workgenerationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_workorder.AfterSingleNum
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer aftersinglenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_workorder.SmallMemberNum
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer smallmembernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_workorder.PickupUnit
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer pickupunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_workorder.PickupTime
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Date pickuptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_workorder.SortingCode
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String sortingcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_workorder.ID
     *
     * @return the value of acc_workorder.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_workorder.ID
     *
     * @param id the value for acc_workorder.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_workorder.BusinessNoticeNo
     *
     * @return the value of acc_workorder.BusinessNoticeNo
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getBusinessnoticeno() {
        return businessnoticeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_workorder.BusinessNoticeNo
     *
     * @param businessnoticeno the value for acc_workorder.BusinessNoticeNo
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setBusinessnoticeno(String businessnoticeno) {
        this.businessnoticeno = businessnoticeno == null ? null : businessnoticeno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_workorder.JobNo
     *
     * @return the value of acc_workorder.JobNo
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getJobno() {
        return jobno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_workorder.JobNo
     *
     * @param jobno the value for acc_workorder.JobNo
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setJobno(String jobno) {
        this.jobno = jobno == null ? null : jobno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_workorder.JobType
     *
     * @return the value of acc_workorder.JobType
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Boolean getJobtype() {
        return jobtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_workorder.JobType
     *
     * @param jobtype the value for acc_workorder.JobType
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setJobtype(Boolean jobtype) {
        this.jobtype = jobtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_workorder.PickupStatus
     *
     * @return the value of acc_workorder.PickupStatus
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Boolean getPickupstatus() {
        return pickupstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_workorder.PickupStatus
     *
     * @param pickupstatus the value for acc_workorder.PickupStatus
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setPickupstatus(Boolean pickupstatus) {
        this.pickupstatus = pickupstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_workorder.ShortMessageInt
     *
     * @return the value of acc_workorder.ShortMessageInt
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getShortmessageint() {
        return shortmessageint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_workorder.ShortMessageInt
     *
     * @param shortmessageint the value for acc_workorder.ShortMessageInt
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setShortmessageint(Integer shortmessageint) {
        this.shortmessageint = shortmessageint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_workorder.WorkGenerationTime
     *
     * @return the value of acc_workorder.WorkGenerationTime
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Date getWorkgenerationtime() {
        return workgenerationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_workorder.WorkGenerationTime
     *
     * @param workgenerationtime the value for acc_workorder.WorkGenerationTime
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setWorkgenerationtime(Date workgenerationtime) {
        this.workgenerationtime = workgenerationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_workorder.AfterSingleNum
     *
     * @return the value of acc_workorder.AfterSingleNum
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getAftersinglenum() {
        return aftersinglenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_workorder.AfterSingleNum
     *
     * @param aftersinglenum the value for acc_workorder.AfterSingleNum
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setAftersinglenum(Integer aftersinglenum) {
        this.aftersinglenum = aftersinglenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_workorder.SmallMemberNum
     *
     * @return the value of acc_workorder.SmallMemberNum
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getSmallmembernum() {
        return smallmembernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_workorder.SmallMemberNum
     *
     * @param smallmembernum the value for acc_workorder.SmallMemberNum
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setSmallmembernum(Integer smallmembernum) {
        this.smallmembernum = smallmembernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_workorder.PickupUnit
     *
     * @return the value of acc_workorder.PickupUnit
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getPickupunit() {
        return pickupunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_workorder.PickupUnit
     *
     * @param pickupunit the value for acc_workorder.PickupUnit
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setPickupunit(Integer pickupunit) {
        this.pickupunit = pickupunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_workorder.PickupTime
     *
     * @return the value of acc_workorder.PickupTime
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Date getPickuptime() {
        return pickuptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_workorder.PickupTime
     *
     * @param pickuptime the value for acc_workorder.PickupTime
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setPickuptime(Date pickuptime) {
        this.pickuptime = pickuptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_workorder.SortingCode
     *
     * @return the value of acc_workorder.SortingCode
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getSortingcode() {
        return sortingcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_workorder.SortingCode
     *
     * @param sortingcode the value for acc_workorder.SortingCode
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setSortingcode(String sortingcode) {
        this.sortingcode = sortingcode == null ? null : sortingcode.trim();
    }
}