package zjs.entity;

import lombok.Data;

import java.util.Date;
@Data
public class BasShuttlebus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_shuttlebus.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_shuttlebus.LineType
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Boolean linetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_shuttlebus.LineID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer lineid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_shuttlebus.LicensePlateInt
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String licenseplateint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_shuttlebus.Carrier
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String carrier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_shuttlebus.Models
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String models;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_shuttlebus.Driver
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String driver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_shuttlebus.Telephone
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_shuttlebus.Ton
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer ton;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_shuttlebus.Remarks
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_shuttlebus.OperatorID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer operatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_shuttlebus.OperationUnitID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer operationunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_shuttlebus.OperationTime
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Date operationtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_shuttlebus.ID
     *
     * @return the value of bas_shuttlebus.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_shuttlebus.ID
     *
     * @param id the value for bas_shuttlebus.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_shuttlebus.LineType
     *
     * @return the value of bas_shuttlebus.LineType
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Boolean getLinetype() {
        return linetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_shuttlebus.LineType
     *
     * @param linetype the value for bas_shuttlebus.LineType
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setLinetype(Boolean linetype) {
        this.linetype = linetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_shuttlebus.LineID
     *
     * @return the value of bas_shuttlebus.LineID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getLineid() {
        return lineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_shuttlebus.LineID
     *
     * @param lineid the value for bas_shuttlebus.LineID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setLineid(Integer lineid) {
        this.lineid = lineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_shuttlebus.LicensePlateInt
     *
     * @return the value of bas_shuttlebus.LicensePlateInt
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getLicenseplateint() {
        return licenseplateint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_shuttlebus.LicensePlateInt
     *
     * @param licenseplateint the value for bas_shuttlebus.LicensePlateInt
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setLicenseplateint(String licenseplateint) {
        this.licenseplateint = licenseplateint == null ? null : licenseplateint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_shuttlebus.Carrier
     *
     * @return the value of bas_shuttlebus.Carrier
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getCarrier() {
        return carrier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_shuttlebus.Carrier
     *
     * @param carrier the value for bas_shuttlebus.Carrier
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setCarrier(String carrier) {
        this.carrier = carrier == null ? null : carrier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_shuttlebus.Models
     *
     * @return the value of bas_shuttlebus.Models
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getModels() {
        return models;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_shuttlebus.Models
     *
     * @param models the value for bas_shuttlebus.Models
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setModels(String models) {
        this.models = models == null ? null : models.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_shuttlebus.Driver
     *
     * @return the value of bas_shuttlebus.Driver
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getDriver() {
        return driver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_shuttlebus.Driver
     *
     * @param driver the value for bas_shuttlebus.Driver
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setDriver(String driver) {
        this.driver = driver == null ? null : driver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_shuttlebus.Telephone
     *
     * @return the value of bas_shuttlebus.Telephone
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_shuttlebus.Telephone
     *
     * @param telephone the value for bas_shuttlebus.Telephone
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_shuttlebus.Ton
     *
     * @return the value of bas_shuttlebus.Ton
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getTon() {
        return ton;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_shuttlebus.Ton
     *
     * @param ton the value for bas_shuttlebus.Ton
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setTon(Integer ton) {
        this.ton = ton;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_shuttlebus.Remarks
     *
     * @return the value of bas_shuttlebus.Remarks
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_shuttlebus.Remarks
     *
     * @param remarks the value for bas_shuttlebus.Remarks
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_shuttlebus.OperatorID
     *
     * @return the value of bas_shuttlebus.OperatorID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_shuttlebus.OperatorID
     *
     * @param operatorid the value for bas_shuttlebus.OperatorID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setOperatorid(Integer operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_shuttlebus.OperationUnitID
     *
     * @return the value of bas_shuttlebus.OperationUnitID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getOperationunitid() {
        return operationunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_shuttlebus.OperationUnitID
     *
     * @param operationunitid the value for bas_shuttlebus.OperationUnitID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setOperationunitid(Integer operationunitid) {
        this.operationunitid = operationunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_shuttlebus.OperationTime
     *
     * @return the value of bas_shuttlebus.OperationTime
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Date getOperationtime() {
        return operationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_shuttlebus.OperationTime
     *
     * @param operationtime the value for bas_shuttlebus.OperationTime
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setOperationtime(Date operationtime) {
        this.operationtime = operationtime;
    }
}