package zjs.entity;

import lombok.Data;

import java.util.Date;
@Data
public class BiglogLogisticscontroltable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biglog_logisticscontroltable.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biglog_logisticscontroltable.WorkSheetNo
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String worksheetno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biglog_logisticscontroltable.CType
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Boolean ctype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biglog_logisticscontroltable.Corporation
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String corporation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biglog_logisticscontroltable.WaybillID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String waybillid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biglog_logisticscontroltable.Remarks
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biglog_logisticscontroltable.InputPerson
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer inputperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biglog_logisticscontroltable.InputDate
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Date inputdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biglog_logisticscontroltable.InputCompany
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer inputcompany;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biglog_logisticscontroltable.ID
     *
     * @return the value of biglog_logisticscontroltable.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biglog_logisticscontroltable.ID
     *
     * @param id the value for biglog_logisticscontroltable.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biglog_logisticscontroltable.WorkSheetNo
     *
     * @return the value of biglog_logisticscontroltable.WorkSheetNo
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getWorksheetno() {
        return worksheetno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biglog_logisticscontroltable.WorkSheetNo
     *
     * @param worksheetno the value for biglog_logisticscontroltable.WorkSheetNo
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setWorksheetno(String worksheetno) {
        this.worksheetno = worksheetno == null ? null : worksheetno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biglog_logisticscontroltable.CType
     *
     * @return the value of biglog_logisticscontroltable.CType
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Boolean getCtype() {
        return ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biglog_logisticscontroltable.CType
     *
     * @param ctype the value for biglog_logisticscontroltable.CType
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setCtype(Boolean ctype) {
        this.ctype = ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biglog_logisticscontroltable.Corporation
     *
     * @return the value of biglog_logisticscontroltable.Corporation
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getCorporation() {
        return corporation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biglog_logisticscontroltable.Corporation
     *
     * @param corporation the value for biglog_logisticscontroltable.Corporation
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setCorporation(String corporation) {
        this.corporation = corporation == null ? null : corporation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biglog_logisticscontroltable.WaybillID
     *
     * @return the value of biglog_logisticscontroltable.WaybillID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getWaybillid() {
        return waybillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biglog_logisticscontroltable.WaybillID
     *
     * @param waybillid the value for biglog_logisticscontroltable.WaybillID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setWaybillid(String waybillid) {
        this.waybillid = waybillid == null ? null : waybillid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biglog_logisticscontroltable.Remarks
     *
     * @return the value of biglog_logisticscontroltable.Remarks
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biglog_logisticscontroltable.Remarks
     *
     * @param remarks the value for biglog_logisticscontroltable.Remarks
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biglog_logisticscontroltable.InputPerson
     *
     * @return the value of biglog_logisticscontroltable.InputPerson
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getInputperson() {
        return inputperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biglog_logisticscontroltable.InputPerson
     *
     * @param inputperson the value for biglog_logisticscontroltable.InputPerson
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setInputperson(Integer inputperson) {
        this.inputperson = inputperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biglog_logisticscontroltable.InputDate
     *
     * @return the value of biglog_logisticscontroltable.InputDate
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Date getInputdate() {
        return inputdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biglog_logisticscontroltable.InputDate
     *
     * @param inputdate the value for biglog_logisticscontroltable.InputDate
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setInputdate(Date inputdate) {
        this.inputdate = inputdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biglog_logisticscontroltable.InputCompany
     *
     * @return the value of biglog_logisticscontroltable.InputCompany
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getInputcompany() {
        return inputcompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biglog_logisticscontroltable.InputCompany
     *
     * @param inputcompany the value for biglog_logisticscontroltable.InputCompany
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setInputcompany(Integer inputcompany) {
        this.inputcompany = inputcompany;
    }
}