package zjs.entity;

import lombok.Data;

import java.util.Date;
@Data
public class DisPropagandatask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_propagandatask.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_propagandatask.Outline
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String outline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_propagandatask.ReleaseTime
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Date releasetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_propagandatask.FailureTime
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Date failuretime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_propagandatask.Status
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_propagandatask.Content
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_propagandatask.ID
     *
     * @return the value of dis_propagandatask.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_propagandatask.ID
     *
     * @param id the value for dis_propagandatask.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_propagandatask.Outline
     *
     * @return the value of dis_propagandatask.Outline
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getOutline() {
        return outline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_propagandatask.Outline
     *
     * @param outline the value for dis_propagandatask.Outline
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setOutline(String outline) {
        this.outline = outline == null ? null : outline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_propagandatask.ReleaseTime
     *
     * @return the value of dis_propagandatask.ReleaseTime
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Date getReleasetime() {
        return releasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_propagandatask.ReleaseTime
     *
     * @param releasetime the value for dis_propagandatask.ReleaseTime
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setReleasetime(Date releasetime) {
        this.releasetime = releasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_propagandatask.FailureTime
     *
     * @return the value of dis_propagandatask.FailureTime
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Date getFailuretime() {
        return failuretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_propagandatask.FailureTime
     *
     * @param failuretime the value for dis_propagandatask.FailureTime
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setFailuretime(Date failuretime) {
        this.failuretime = failuretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_propagandatask.Status
     *
     * @return the value of dis_propagandatask.Status
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_propagandatask.Status
     *
     * @param status the value for dis_propagandatask.Status
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_propagandatask.Content
     *
     * @return the value of dis_propagandatask.Content
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_propagandatask.Content
     *
     * @param content the value for dis_propagandatask.Content
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}