package zjs.entity;

import lombok.Data;

import java.util.Date;
@Data
public class LogLogisticsdetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_logisticsdetails.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_logisticsdetails.LogisticsInt
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String logisticsint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_logisticsdetails.CompanyName
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String companyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_logisticsdetails.ColumnExpectArrivalDate_4
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Date columnexpectarrivaldate4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_logisticsdetails.ActualArrivalDate
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Date actualarrivaldate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_logisticsdetails.ExpectDepartureDate
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Date expectdeparturedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_logisticsdetails.ActualDepartureDate
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Date actualdeparturedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_logisticsdetails.OperationPerson
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String operationperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_logisticsdetails.LogisticsType
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String logisticstype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_logisticsdetails.ID
     *
     * @return the value of log_logisticsdetails.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_logisticsdetails.ID
     *
     * @param id the value for log_logisticsdetails.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_logisticsdetails.LogisticsInt
     *
     * @return the value of log_logisticsdetails.LogisticsInt
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getLogisticsint() {
        return logisticsint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_logisticsdetails.LogisticsInt
     *
     * @param logisticsint the value for log_logisticsdetails.LogisticsInt
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setLogisticsint(String logisticsint) {
        this.logisticsint = logisticsint == null ? null : logisticsint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_logisticsdetails.CompanyName
     *
     * @return the value of log_logisticsdetails.CompanyName
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_logisticsdetails.CompanyName
     *
     * @param companyname the value for log_logisticsdetails.CompanyName
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname == null ? null : companyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_logisticsdetails.ColumnExpectArrivalDate_4
     *
     * @return the value of log_logisticsdetails.ColumnExpectArrivalDate_4
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Date getColumnexpectarrivaldate4() {
        return columnexpectarrivaldate4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_logisticsdetails.ColumnExpectArrivalDate_4
     *
     * @param columnexpectarrivaldate4 the value for log_logisticsdetails.ColumnExpectArrivalDate_4
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setColumnexpectarrivaldate4(Date columnexpectarrivaldate4) {
        this.columnexpectarrivaldate4 = columnexpectarrivaldate4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_logisticsdetails.ActualArrivalDate
     *
     * @return the value of log_logisticsdetails.ActualArrivalDate
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Date getActualarrivaldate() {
        return actualarrivaldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_logisticsdetails.ActualArrivalDate
     *
     * @param actualarrivaldate the value for log_logisticsdetails.ActualArrivalDate
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setActualarrivaldate(Date actualarrivaldate) {
        this.actualarrivaldate = actualarrivaldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_logisticsdetails.ExpectDepartureDate
     *
     * @return the value of log_logisticsdetails.ExpectDepartureDate
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Date getExpectdeparturedate() {
        return expectdeparturedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_logisticsdetails.ExpectDepartureDate
     *
     * @param expectdeparturedate the value for log_logisticsdetails.ExpectDepartureDate
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setExpectdeparturedate(Date expectdeparturedate) {
        this.expectdeparturedate = expectdeparturedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_logisticsdetails.ActualDepartureDate
     *
     * @return the value of log_logisticsdetails.ActualDepartureDate
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Date getActualdeparturedate() {
        return actualdeparturedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_logisticsdetails.ActualDepartureDate
     *
     * @param actualdeparturedate the value for log_logisticsdetails.ActualDepartureDate
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setActualdeparturedate(Date actualdeparturedate) {
        this.actualdeparturedate = actualdeparturedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_logisticsdetails.OperationPerson
     *
     * @return the value of log_logisticsdetails.OperationPerson
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getOperationperson() {
        return operationperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_logisticsdetails.OperationPerson
     *
     * @param operationperson the value for log_logisticsdetails.OperationPerson
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setOperationperson(String operationperson) {
        this.operationperson = operationperson == null ? null : operationperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_logisticsdetails.LogisticsType
     *
     * @return the value of log_logisticsdetails.LogisticsType
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getLogisticstype() {
        return logisticstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_logisticsdetails.LogisticsType
     *
     * @param logisticstype the value for log_logisticsdetails.LogisticsType
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setLogisticstype(String logisticstype) {
        this.logisticstype = logisticstype == null ? null : logisticstype.trim();
    }
}