package zjs.entity;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;
@Data
public class SorPackagedetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sor_packagedetails.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sor_packagedetails.WareName
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer warename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sor_packagedetails.Destination
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String destination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sor_packagedetails.Ticket
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer ticket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sor_packagedetails.ActualCargoInt
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer actualcargoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sor_packagedetails.CargoInt
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer cargoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sor_packagedetails.Weight
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private BigDecimal weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sor_packagedetails.Volume
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private BigDecimal volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sor_packagedetails.Service
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Date service;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sor_packagedetails.ImportantHints
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String importanthints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sor_packagedetails.Ask
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String ask;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sor_packagedetails.InputType
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String inputtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sor_packagedetails.ID
     *
     * @return the value of sor_packagedetails.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sor_packagedetails.ID
     *
     * @param id the value for sor_packagedetails.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sor_packagedetails.WareName
     *
     * @return the value of sor_packagedetails.WareName
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getWarename() {
        return warename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sor_packagedetails.WareName
     *
     * @param warename the value for sor_packagedetails.WareName
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setWarename(Integer warename) {
        this.warename = warename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sor_packagedetails.Destination
     *
     * @return the value of sor_packagedetails.Destination
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sor_packagedetails.Destination
     *
     * @param destination the value for sor_packagedetails.Destination
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setDestination(String destination) {
        this.destination = destination == null ? null : destination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sor_packagedetails.Ticket
     *
     * @return the value of sor_packagedetails.Ticket
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getTicket() {
        return ticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sor_packagedetails.Ticket
     *
     * @param ticket the value for sor_packagedetails.Ticket
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setTicket(Integer ticket) {
        this.ticket = ticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sor_packagedetails.ActualCargoInt
     *
     * @return the value of sor_packagedetails.ActualCargoInt
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getActualcargoint() {
        return actualcargoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sor_packagedetails.ActualCargoInt
     *
     * @param actualcargoint the value for sor_packagedetails.ActualCargoInt
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setActualcargoint(Integer actualcargoint) {
        this.actualcargoint = actualcargoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sor_packagedetails.CargoInt
     *
     * @return the value of sor_packagedetails.CargoInt
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getCargoint() {
        return cargoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sor_packagedetails.CargoInt
     *
     * @param cargoint the value for sor_packagedetails.CargoInt
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setCargoint(Integer cargoint) {
        this.cargoint = cargoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sor_packagedetails.Weight
     *
     * @return the value of sor_packagedetails.Weight
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sor_packagedetails.Weight
     *
     * @param weight the value for sor_packagedetails.Weight
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sor_packagedetails.Volume
     *
     * @return the value of sor_packagedetails.Volume
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public BigDecimal getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sor_packagedetails.Volume
     *
     * @param volume the value for sor_packagedetails.Volume
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setVolume(BigDecimal volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sor_packagedetails.Service
     *
     * @return the value of sor_packagedetails.Service
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Date getService() {
        return service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sor_packagedetails.Service
     *
     * @param service the value for sor_packagedetails.Service
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setService(Date service) {
        this.service = service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sor_packagedetails.ImportantHints
     *
     * @return the value of sor_packagedetails.ImportantHints
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getImportanthints() {
        return importanthints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sor_packagedetails.ImportantHints
     *
     * @param importanthints the value for sor_packagedetails.ImportantHints
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setImportanthints(String importanthints) {
        this.importanthints = importanthints == null ? null : importanthints.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sor_packagedetails.Ask
     *
     * @return the value of sor_packagedetails.Ask
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getAsk() {
        return ask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sor_packagedetails.Ask
     *
     * @param ask the value for sor_packagedetails.Ask
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setAsk(String ask) {
        this.ask = ask == null ? null : ask.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sor_packagedetails.InputType
     *
     * @return the value of sor_packagedetails.InputType
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getInputtype() {
        return inputtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sor_packagedetails.InputType
     *
     * @param inputtype the value for sor_packagedetails.InputType
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setInputtype(String inputtype) {
        this.inputtype = inputtype == null ? null : inputtype.trim();
    }
}