package zjs.entity;

import lombok.Data;

@Data
public class SyMenus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_menus.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_menus.parentID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_menus.type
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_menus.text
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_menus.url
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_menus.tip
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String tip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_menus.ID
     *
     * @return the value of sy_menus.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_menus.ID
     *
     * @param id the value for sy_menus.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_menus.parentID
     *
     * @return the value of sy_menus.parentID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_menus.parentID
     *
     * @param parentid the value for sy_menus.parentID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_menus.type
     *
     * @return the value of sy_menus.type
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_menus.type
     *
     * @param type the value for sy_menus.type
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_menus.text
     *
     * @return the value of sy_menus.text
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_menus.text
     *
     * @param text the value for sy_menus.text
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_menus.url
     *
     * @return the value of sy_menus.url
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_menus.url
     *
     * @param url the value for sy_menus.url
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_menus.tip
     *
     * @return the value of sy_menus.tip
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getTip() {
        return tip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_menus.tip
     *
     * @param tip the value for sy_menus.tip
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setTip(String tip) {
        this.tip = tip == null ? null : tip.trim();
    }
}