package zjs.entity;

import lombok.Data;

import java.util.Date;
@Data
public class SyUnits {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_units.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_units.Name
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_units.Remarks
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_units.OperatorID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Integer operatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_units.OperationTime
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    private Date operationtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_units.ID
     *
     * @return the value of sy_units.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_units.ID
     *
     * @param id the value for sy_units.ID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_units.Name
     *
     * @return the value of sy_units.Name
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_units.Name
     *
     * @param name the value for sy_units.Name
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_units.Remarks
     *
     * @return the value of sy_units.Remarks
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_units.Remarks
     *
     * @param remarks the value for sy_units.Remarks
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_units.OperatorID
     *
     * @return the value of sy_units.OperatorID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Integer getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_units.OperatorID
     *
     * @param operatorid the value for sy_units.OperatorID
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setOperatorid(Integer operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_units.OperationTime
     *
     * @return the value of sy_units.OperationTime
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public Date getOperationtime() {
        return operationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_units.OperationTime
     *
     * @param operationtime the value for sy_units.OperationTime
     *
     * @mbggenerated Sat Jan 04 11:21:18 CST 2020
     */
    public void setOperationtime(Date operationtime) {
        this.operationtime = operationtime;
    }
}